# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSamples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for RxSamples

  target 'RxSamplesTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxTest'
  end

  target 'RxKit' do
    pod 'RxSwift'

    target 'RxKitTests' do
      inherit! :search_paths

      pod 'RxTest'
    end

  end

end
